version: '3'

services:
    apache:
        build: ./images/httpd
        volumes:
            - ./www:/var/www/html
            - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
        ports:
            - "66:80"
        depends_on:
            - php
        networks:
            - main_network
    nginx:
        build: ./images/nginx
        ports:
            - "88:80"
            - "443:443"
        #command: mkdir /var/certs
        volumes:
            - ./hosts/nginx.conf:/etc/nginx/nginx.conf
            - ./www:/var/www/html
            - ./logs/nginx:/var/log/nginx
            #- ./hosts/certs/:/var/
        depends_on:
            - apache
        networks:
            - main_network

    php:
        build: ./images/php
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_DATABASE=sait
            - MYSQL_USER=root
            - MYSQL_PASSWORD=123
        depends_on:
            -   mysql
        volumes:
            - ./www:/var/www/html
        networks:
            - main_network
    mysql:
        build: ./images/mysql
        ports:
            - "3306:3306"
        volumes:
            - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
            - ./logs/mysql:/var/log/mysql
            - ./mysql-files:/var/lib/mysql-files
            - ./data:/docker-entrypoint-initdb.d
            - dbdata:/var/lib/mysql/ # если мы упороты и хотим наблюдать безобразие =) - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: sait
        networks:
            - main_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:db
        ports:
            - 8765:80
        environment:
            MYSQL_ROOT_PASSWORD: qwerty
        depends_on:
            - mysql
        #networks:
        #    - main_network

networks:
    main_network:
        driver: bridge

volumes:
    dbdata:
        driver: local